### ISSUE TITLE
any way to add it on my agario web clone ??

### ISSUE THREAD

**Issue by wayfarer2** [Megabyte918/Agar.io-Custom-Skins#1]
Hi there i have a webclient wich im using multiogar to run the server but i want to add the Custom-skins to my webclient .
im hoping that players can use any skin they want when they join but i dont know how 
please help me .... Thanks and sry for my bad english

**Comment by Fan7asy** [comment]
@wayfarer2 No there isn't a way for you to add it to your clone.

**Comment by m-byte918** [comment]
In order for this to happen, each player will have to have the script installed. Either that or implement a custom skins system into the client itself.
